api/urls.py
from django.urls import path
from rest_framework.authtoken.views import obtain_auth_token

from config.base import API_VERSION

from .views import (AnswerDetailsAPIView, AnswersAPIView, AnswerVotesAPIView,
                    QuestionAPIView, QuestionDetailsAPIView,
                    QuestionVotesAPIView)

app_name = 'apiapp'

urlpatterns = [
    path(f'{API_VERSION}/token', obtain_auth_token, name='api_obtain_token'),
    path(f'{API_VERSION}/questions/', QuestionAPIView.as_view(), name='api_questions'),
    path(f'{API_VERSION}/questions/<int:pk>/', QuestionDetailsAPIView.as_view(), name='api_question_details'),
    path(f'{API_VERSION}/questions/<int:pk>/answers', AnswersAPIView.as_view(), name='api_answers'),
    path(f'{API_VERSION}/questions/<int:pk>/votes', QuestionVotesAPIView.as_view(), name='api_question_votes'),
    path(f'{API_VERSION}/answers/<int:pk>', AnswerDetailsAPIView.as_view(), name='api_answer_details'),
    path(f'{API_VERSION}answers/<int:pk>/votes', AnswerVotesAPIView.as_view(), name='api_answer_votes'),
 ]

questions/urls.py
from django.urls import path

from .views import (
        QuestionsListView, QuestionDetailView, QuestionTopView, 
        QuestionSearch, AskView, QuestionsTag, QuestionUserView,
        approved_answer, vote_answer, vote_question 
    )


app_name = "question"


urlpatterns = [
    path("", QuestionsListView.as_view(), name="index"),
    path("top/", QuestionTopView.as_view(), name="top_question"),
    path("question/<str:slug>/", QuestionDetailView.as_view(), name="question"),
    path("question/published/<username>/", QuestionUserView.as_view(), name="question_user"),
    path("search/", QuestionSearch.as_view(), name="search"),
    path("ask/", AskView.as_view(), name="ask"),
    path("tag/<slug>", QuestionsTag.as_view(), name="tag"),
]

# Urlpatterns AJAX
urlpatterns += [
    path("vote_answer/", vote_answer, name="vote_answer"),
    path("vote_question/", vote_question, name="vote_question"),
    path("approved_answer/<int:pk>", approved_answer, name="approved_answer"),
]

questions/models.py
from django.contrib.auth import get_user_model
from django.core.exceptions import ObjectDoesNotExist
from django.db import models
from django.db.models import Count

from config.base import VOTE_DOWN, VOTE_UP

User = get_user_model()


VOTE_CHOICES = ((VOTE_UP, "Vote Up"), (VOTE_DOWN, "Vote Down"))


class AbstactPost(models.Model):
    """
    Abstract model that defines common fields and methods
    for Question / Answer models.
    """
    
    class Meta:
        abstract = True
        ordering = ["-date_publication"]

    vote_class = None
    author = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name="%(class)s",
    )
    description = models.TextField(blank=False)
    date_publication = models.DateTimeField(auto_now_add=True)
    rating = models.IntegerField(default=0)


    def change_vote(self, user, value):
        """Add, cancel, delete vote to current rating."""

        try:
            current = self.vote_class.objects.get(to=self, author=user)
        except ObjectDoesNotExist:
            self.vote_class.objects.create(to=self, author=user, value_vote=value)
            current = self.vote_class.objects.get(to=self, author=user)
            self.rating += value
            return self.rating

        if current.value_vote == value:
            return self.rating

        self.vote_class.objects.filter(to=self, author=user).delete()
        self.rating += value
        return self.rating


class AbstractVote(models.Model):
    """
    Abstract model that defines common fields and methods
    for QuestionVote / AnswerVote models.
    """

    class Meta:
        abstract = True

    time_vote = models.DateField(auto_now=True)
    value_vote = models.SmallIntegerField(choices=VOTE_CHOICES)
    author = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name="%(class)s",
    )


class QuestionVote(AbstractVote):
    to = models.ForeignKey(
        "Question",
        on_delete=models.CASCADE,
        related_name="votes",
        related_query_name="votes",
    )


class AnswerVote(AbstractVote):
    to = models.ForeignKey(
        "Answer",
        on_delete=models.CASCADE,
        related_name="votes",
        related_query_name="votes",
    )


class QuestionManager(models.Manager):
    def get_queryset(self):
        """ Returns annotated qweryset: answers_count."""
        queryset = super().get_queryset().annotate(
            answers_count=Count("answer")
        )
        return queryset


class Question(AbstactPost):
    vote_class = QuestionVote
    title = models.CharField(blank=False, max_length=256)
    tags = models.ManyToManyField("Tag", blank=True)

    objects = models.Manager()
    hewy = QuestionManager()

    def __str__(self):
        return self.title

    @classmethod
    def trending(cls, count = 10):
        """ Returns a query set of trending questions."""

        return cls.objects.order_by("-rating")[:count]

    def add_tags(self, tags):
        for tag in set(tags):
            try:
                tag = Tag.objects.get(name=tag)
            except ObjectDoesNotExist:
                tag = Tag.objects.create(name=tag)
            self.tags.add(tag)


class Answer(AbstactPost):
    vote_class = AnswerVote
    question = models.ForeignKey(
        Question,
        related_name="answer",
        on_delete=models.CASCADE,
    )
    is_accepted = models.BooleanField(default=False)


    def accepted(self):
        """Accept answer"""

        self.question.answer.update(is_accepted=False)
        self.is_accepted = True
        self.save(update_fields=["is_accepted"])


    def unaccepted(self):
        """Cansel answer"""

        self.is_accepted = False
        self.save(update_fields=["is_accepted"])

    def __str__(self):
        return self.question.title


class Tag(models.Model):
    name = models.CharField(unique=True, max_length=15)

    def __str__(self):
        return self.name

questions/forms.py
from django import forms
from django.core.exceptions import ObjectDoesNotExist
from .models import Question, Answer, VOTE_CHOICES


MAX_COUNT_POST_TAGS = 3
MAX_LENGTH_POST_TAGS = 15

class AnswerForm(forms.ModelForm):
    class Meta:
        model = Answer
        fields = ("description",)


class SearchForm(forms.Form):
    search_ = forms.CharField(max_length = 254)


class AskForm(forms.ModelForm):
    tags = forms.CharField(max_length=254, required=False)

    class Meta:
        model = Question
        fields = ("title", "description",)

    def clean_title(self):
        title = self.cleaned_data["title"]

        try:
            Question.objects.get(title__iexact=title.strip())
        except ObjectDoesNotExist:
            return title
        raise forms.ValidationError("A topic with the same name already exists.")

    def clean_tags(self):
        tags = self.cleaned_data["tags"]
        tags = [tag.lower().strip() for tag in tags.split(',') if tag]

        if len(tags) > MAX_COUNT_POST_TAGS:
            raise forms.ValidationError(
                f"You cannot post more than {MAX_COUNT_POST_TAGS} tags")

        if tags and max(map(len, tags)) > MAX_LENGTH_POST_TAGS:
            raise forms.ValidationError(
                f"Maximum tag length no more than {MAX_LENGTH_POST_TAGS} characters")

        return tags


class VoteForm(forms.Form):
    target_id = forms.IntegerField()
    value = forms.TypedChoiceField(choices=VOTE_CHOICES, coerce=int)

questions/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.db import transaction
from django.db.models import Q
from django.http import Http404, HttpResponseForbidden, JsonResponse, request
from django.shortcuts import get_object_or_404, redirect
from django.urls import reverse_lazy
from django.views.generic import CreateView
from django.views.generic.list import ListView

from config.base import PAGITATE_BY
from users.mixins import UserRequired

from .forms import AnswerForm, AskForm, SearchForm, VoteForm
from .mixins import TredingMixin
from .models import Answer, Question


class QuestionsListView(TredingMixin, ListView):
    """ List of all questions sorted default: -date_publication."""

    model = Question
    template_name = "questions/index.html"
    paginate_by = PAGITATE_BY

    def get_queryset(self):
        queryset = Question.hewy.all()
        return queryset.select_related("author").prefetch_related("tags")


class QuestionTopView(QuestionsListView):
    """ List of all questions sorted rating."""

    def get_queryset(self):
        queryset = super().get_queryset()
        return queryset.order_by("-rating",)


class QuestionUserView(QuestionsListView):
    """ List of questions current user."""

    ordering = ("-rating",)

    def get_queryset(self):
        queryset = super().get_queryset()
        username = self.kwargs["username"]
        return queryset.filter(author__username=username)


class QuestionsTag(QuestionsListView):
    """ List of questions current tag."""
    
    ordering = ("-rating",)

    def get_queryset(self):
        queryset = super().get_queryset()
        tag = self.kwargs["slug"].strip().lower()
        return queryset.filter(tags__name=tag)


class QuestionDetailView(TredingMixin, ListView):
    """ Question details / list answer. """

    form = None
    model = Answer
    ordering = ("date_publication", "-rating",)
    template_name = "questions/question.html"
    paginate_by = PAGITATE_BY
    login_url = reverse_lazy("users:login")


    def dispatch(self, *args, **kwargs):
        self.question = get_object_or_404(Question, title=self.kwargs["slug"])
        return super().dispatch(*args, **kwargs)

    def get_queryset(self):
        queryset = super().get_queryset()
        queryset = queryset.filter(question=self.question)
        self.answers_count = queryset.count()
        return queryset

    def get_context_data(self, *args, **kwargs):
        context = super().get_context_data(*args, **kwargs)
        context["question"] = self.question
        context["answers_count"] = self.answers_count
        return context

    def post(self, *args, **kwargs):
        if not self.request.user.is_authenticated:
            return redirect("users:login")
        
        form = AnswerForm(data=self.request.POST)
        if form.is_valid():
            return self.form_valid(form)
        return self.form_invalid(form)

    @transaction.atomic
    def form_valid(self, form):
        answer = form.save(commit=False)
        answer.author = self.request.user
        answer.question = self.question
        answer.save()
        return redirect(self.request.build_absolute_uri())

    def form_invalid(self, form):
        self.rorm = form
        return super().get(self.request)


class QuestionSearch(QuestionsListView):
    """
    Search by title and description of questions.
    Search for tag related questions
    """

    search = ""
    def get(self, *args, **kwargs):
        self.search = self.request.GET.get("search_")

        if self.search.startswith("tag:"):                #search tag
            _, tag = self.search.split("tag:")
            tag = tag.lower().strip()
            return redirect("question:tag", slug=tag)
        return super().get(*args, **kwargs)

    def get_queryset(self):
        queryset = super().get_queryset()
        form = SearchForm(self.request.GET)
        if form.is_valid():
            queryset = queryset.filter(
                Q(title__icontains=self.search) | Q(description__icontains=self.search)
            )
        return queryset


class AskView(TredingMixin, LoginRequiredMixin, CreateView):
    """ View add answer. """

    form_class = AskForm
    model = Question
    template_name = "questions/ask.html"
    success_url = reverse_lazy("question:index")
    login_url = reverse_lazy("users:login")

    @transaction.atomic
    def form_valid(self, form):
        question = form.save(commit=False)
        question.author = self.request.user
        question.save()

        tags = form.cleaned_data["tags"]
        question.add_tags(tags)

        return redirect(self.success_url)


def vote_answer(request):
    """Vote for a answer. Only AJAX request by post method."""

    form = VoteForm(request.POST)
    if form.is_valid() and request.is_ajax():
        target = form.cleaned_data["target_id"]
        value = form.cleaned_data["value"]

        pub = Question.objects.get(id=target)
        rating = pub.change_vote(value=value, user=request.user)
        pub.rating = rating
        pub.vlue_vote = value
        pub.save()
        return JsonResponse(data={"rating": rating})

    return JsonResponse(data=form.errors, status=400)


def vote_question(request):
    """Vote for a question. Only AJAX request by post method."""

    form = VoteForm(request.POST)
    if form.is_valid() and request.is_ajax():
        if not request.user.is_authenticated:

            return HttpResponseForbidden()

        target = form.cleaned_data["target_id"]
        value = form.cleaned_data["value"]

        pub = Answer.objects.get(id=target)
        rating = pub.change_vote(value=value, user=request.user)
        pub.rating = rating
        pub.vlue_vote = value
        pub.save()
        return JsonResponse(data={"rating": rating})

    return JsonResponse(data=form.errors, status=400)


def approved_answer(request, pk):
    """Approved answer. Only AJAX request by post method."""
    
    if not request.user.is_authenticated:
        return HttpResponseForbidden()

    if request.method == "POST" and request.is_ajax():
        answer = Answer.objects.get(id=pk)

        if answer.question.author != request.user:
            return HttpResponseForbidden()

        if answer.is_accepted:
            answer.unaccepted()
        else:
            answer.accepted()

        return JsonResponse(data={"is_accepted": answer.is_accepted})

questions/templates/questions/ask.html
{% extends 'base.html' %}

{% block content %}
<h2>Ask a public question</h2>

<form method="POST">
    <div class="form-group">
      <label for="formGroupExampleInput">Title</label>
      <input 
        type="text"
        class="form-control"
        id="formGroupExampleInput"
        name="title"
        placeholder="Be specific and imagine you’re asking a question to another person"
        required=Tue
        {% if form.title.value != None %}value="{{ form.title.value }}"{% endif %}
      >
      {% if form.title.errors %}
      <div class="text-danger">{{ form.title.errors }}</div>
      {% endif %}
    </div>
    <div class="form-group shadow-textarea">
        <label for="formGroupExampleInput">Description</label>
        <textarea class="form-control z-depth-1" id="exampleFormControlTextarea6" rows="5" name="description" text="" placeholder="Include all the information someone would need to answer your question" required=True>{% if form.description.value != None %}{{ form.description.value }} {% endif %}</textarea>
        {% if form.description.errors %}
        <div class="text-danger">{{ form.description.errors }}</div>
        {% endif %}
    </div>
    <div class="form-group">
      <label for="formGroupExampleInput2">Tags</label>
      <input
        type="text"
        class="form-control"
        id="formGroupExampleInput2"
        name="tags"
        placeholder="Add up to 5 tags to describe what your question is about (python, js, server)"
        {% if form.tags.value != None %}value="{{ form.tags.value }}"{% endif %}
      >
      {% if form.tags.errors %}
      <div class="text-danger">{{ form.tags.errors }}</div>
      {% endif %}
    </div>
    <button class="btn btn-primary">Ask</button>
    {% csrf_token %}
  </form>

{% endblock %}

questions/templates/questions/index.html
{% extends 'base.html' %}
{% load static %}

{% block content %}

  <div class="row">
    <div class="d-flex justify-content-center col-sm">
      <a href="{% url 'question:index' %}" style="font-size:25px" class="badge badge-light item">New questions</a>
    </div>
    <div class="d-flex justify-content-center col-sm">
      <a href="{% url 'question:top_question' %}?order=votes" style="font-size:25px" class="badge badge-light item">Hot questions</a>
    </div>
  </div>
  <hr>
  <h2>Questions</h2>
  {% for question in question_list %}
    <div class="row">
      <div class="col-1 text-center">
        {{ question.rating }}
        Vote{{ question.rating|pluralize }}
      </div>
      <div class="col-2 text-center">
        {{ question.answers_count }} <br>
        Answer{{ question.answers_count|pluralize }}
      </div>
      <div class="col">
        <a href="{% url 'question:question' slug=question.title %}">{{ question.title }}</a><br>
        <div class="short-description">
          {% if question.description|length > 150 %}
          {{ question.description|slice:":150"}} ...
          {% else %}
          {{ question.description }}
          {% endif %}
        </div>
        {% for tag in question.tags.all %}
        <a class="badge badge-primary" href="{% url 'question:tag' slug=tag.name %}">{{ tag }}</a>
        {% endfor %}
      </div>
      <div class="col-3 text-center">
        <a href="{% url 'question:question_user' username=question.author %}">{{ question.author }}</a>
        <p class="font-weight-bold text-center", style="font-size:10px" > asked {{ question.date_publication|timesince }} ago</p>
      </div>
    </div>
    <hr>
  {% endfor %}
  {% include 'questions/pagination.html' with page=page_obj page_range=page_obj.paginator.page_range %}
{% endblock %}

questions/templates/questions/pagination.html
<nav aria-label="Page navigation example">
    <ul class="pagination pg-blue">
    <li class="page-item">
        <a class="page-link" {% if page.has_previous %} onclick="return true" href="?page={{ page.previous_page_number }}"{% else %} onclick="return false" {% endif %} >Previous</a>
    </li>
    {% for number in page_range %}
    <li class="page-item">
        <a class="page-link" href="?page={{ number }}">{{ number }}</a>
    </li>
    {% endfor %}
    <li class="page-item">
        <a class="page-link" {% if page.has_next %} onclick="return true" href="?page={{ page.next_page_number }}"{% else %} onclick="return false" {% endif %} >Next</a>
    </li>
    </ul>
  </nav>

questions/templates/questions/question.html
{% extends 'base.html' %}

{% block content %}


<div class="row">
  <div class="col-1 text-center">
    <div class="votes" data-target="{{ question.pk }}" data-url="{% url 'question:vote_answer' %}">
      <div class="rating--UP-DOWN" nane="up_booton" data-value="1">
          <ion-icon class="icon-arrow" name="chevron-up-outline" size="large"></ion-icon>
      </div>
      <span class="ratig">{{ question.rating }}</span>
      <div class="rating--UP-DOWN" nane="down_booton" data-value="-1" >
          <ion-icon class="icon-arrow" name="chevron-down-outline" size="large" ></ion-icon>
      </div>
    </div>
  </div>
  <div class="col">
  <h3>{{ question.title }}</h3>
  <p>{{ question.description }}</p>
  {% for tag in question.tags.all %}
    <a class="badge badge-primary" href="{% url 'question:tag' slug=tag.name %}">{{ tag }}</a>
  {% endfor %}
  </div>
</div>
  <div class="row">
    <div class="col-9">
    </div>
    <div class="col">
      <img src="{{ question.author.photo.url }}" alt="" class="rounded float-right " width="50" height="50">
      <a href="{% url 'question:question_user' username=question.author %}">{{  question.author }}</a>
      <p class="date-time" >{{ question.date_publication }}</p>
    </div>
  </div>
<hr>
<p class="font-weight-bold">{{ answers_count }} answer{{ answers_count|pluralize }}</p>
<br>
  {% for answer in answer_list %}
  <div class="row">
    <div class="col-1 text-center">
      <div class="votes" data-target="{{ answer.pk }}" data-url="{% url 'question:vote_question' %}">
        <div class="rating--UP-DOWN" nane="up_booton" data-value="1">
            <ion-icon class="icon-arrow" name="chevron-up-outline" size="large"></ion-icon>
        </div>
        <span class="ratig">{{ answer.rating }}</span>
        <div class="rating--UP-DOWN" nane="down_booton" data-value="-1" >
            <ion-icon class="icon-arrow" name="chevron-down-outline" size="large" ></ion-icon>
        </div>
        
        {% if request.user == question.author %}
          <div class="approve-answ {% if answer.is_accepted %}is_accepted-mark{% endif %}" data-url="{% url 'question:approved_answer' pk=answer.pk %}">
            <ion-icon class="icn" name="checkmark-outline" size="large"></ion-icon>
          </div>
        {% elif answer.is_accepted %}
          <div class="approve-answ {% if answer.is_accepted %}is_accepted-mark{% endif %}">
            <ion-icon class="icn" name="checkmark-outline" size="large"></ion-icon>
          </div>
        {% endif %}
      </div>
    </div>
    <div class="col">
      {{ answer.description }}
    </div>
  </div>
  <div class="row">
    <div class="col-9">
    </div>
    <div class="col">
      <img src="{{ answer.author.photo.url }}" alt="" class="rounded float-right" width="50" height="50">
      <a href="{% url 'question:question_user' username=answer.author %}">{{ answer.author }}</a>
      <p class="date-time">{{ answer.date_publication }}</p>
    </div>
  </div>
  <hr>
  {% endfor %}
   {% for error in form.non_field_errors %}
    {{error}}
  {% endfor %}
   <h3>Your answer</h3>
  <form method="POST">
    <div class="form-group shadow-textarea">
        <textarea class="form-control z-depth-1" id="exampleFormControlTextarea6" rows="4" name="description" placeholder="Write your answer here..."></textarea>
        {% if form.description.errors %}
        <div class="uk-form-danger">{{ form.description.errors }}</div>
        {% endif %}
    </div>
      <button class="btn btn-primary">Answer</button>
    {% csrf_token %}
</form>
<br>
{% include 'questions/pagination.html' with page=page_obj page_range=page_obj.paginator.page_range %}

{% endblock %}