api/urls.py
from django.urls import path
from rest_framework.authtoken.views import obtain_auth_token

from config.base import API_VERSION

from .views import (AnswerDetailsAPIView, AnswersAPIView, AnswerVotesAPIView,
                    QuestionAPIView, QuestionDetailsAPIView,
                    QuestionVotesAPIView)

app_name = 'apiapp'

urlpatterns = [
    path(f'{API_VERSION}/token', obtain_auth_token, name='api_obtain_token'),
    path(f'{API_VERSION}/questions/', QuestionAPIView.as_view(), name='api_questions'),
    path(f'{API_VERSION}/questions/<int:pk>/', QuestionDetailsAPIView.as_view(), name='api_question_details'),
    path(f'{API_VERSION}/questions/<int:pk>/answers', AnswersAPIView.as_view(), name='api_answers'),
    path(f'{API_VERSION}/questions/<int:pk>/votes', QuestionVotesAPIView.as_view(), name='api_question_votes'),
    path(f'{API_VERSION}/answers/<int:pk>', AnswerDetailsAPIView.as_view(), name='api_answer_details'),
    path(f'{API_VERSION}answers/<int:pk>/votes', AnswerVotesAPIView.as_view(), name='api_answer_votes'),
 ]

questions/urls.py
from django.urls import path

from .views import (
        QuestionsListView, QuestionDetailView, QuestionTopView, 
        QuestionSearch, AskView, QuestionsTag, QuestionUserView,
        approved_answer, vote_answer, vote_question 
    )


app_name = "question"


urlpatterns = [
    path("", QuestionsListView.as_view(), name="index"),
    path("top/", QuestionTopView.as_view(), name="top_question"),
    path("question/<str:slug>/", QuestionDetailView.as_view(), name="question"),
    path("question/published/<username>/", QuestionUserView.as_view(), name="question_user"),
    path("search/", QuestionSearch.as_view(), name="search"),
    path("ask/", AskView.as_view(), name="ask"),
    path("tag/<slug>", QuestionsTag.as_view(), name="tag"),
]

# Urlpatterns AJAX
urlpatterns += [
    path("vote_answer/", vote_answer, name="vote_answer"),
    path("vote_question/", vote_question, name="vote_question"),
    path("approved_answer/<int:pk>", approved_answer, name="approved_answer"),
]

users/urls.py
from django.urls import path

from .views import SignUpView, Settings, AccountLogoutView, AccountLoginView

app_name = 'users'


urlpatterns = [
    path("signup/", SignUpView.as_view(), name="signup"),
    path("settings/", Settings.as_view(), name="settings"),
    path("logout/", AccountLogoutView.as_view(), name="logout"),
    path("login/", AccountLoginView.as_view(), name="login"),
]

templates/base.html
{% load static %}

<!doctype html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet"> 
  <link href="{% static 'css/main.css' %}" rel="stylesheet"> 


  <title>{% block title %}
    {% endblock %}
  </title>
</head>
<body>

  <div class="container">
    <nav class="navbar navbar-light bg-light">
      <a class="navbar-brand" style="font-size:35px" href="{% url 'question:index' %}">Hasker</a>
      <form class="form-inline" method="get" action="{% url 'question:search' %}">
        {% csrf_token %}
        <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search" name="search_">
        <button class="btn btn-outline-primary my-2 my-sm-0" type="submit">Search</button>
      </form>
      {% if request.user.is_authenticated %}
      <div>
        <div class="d-inline-block">
          <a class="nav-link " href="{% url 'users:settings' %}"><img src="{{ request.user.photo.url }}" alt="" class="rounded float-right" width="50" height="50"></a>
          
        </div>
        <div class="d-inline-block">
          <a class="nav-link " href="{% url 'users:settings' %}">{{ request.user }}</a>
          <a class="nav-link " href="{% url 'users:logout' %}"><ion-icon name="exit-outline" size="large"></ion-icon></a>
        </div>
      </div>
      {% else %}
      <div class="d-flex justify-content-end">
        <a class="nav-link my-2 my-sm-0" href="{% url 'users:login' %}">Log in</a>
        <a class="nav-link btn btn-outline-primary my-2 my-sm-0" href="{% url 'users:signup' %}">Sign up</a>
      </div>
      {% endif %}
    </nav>
    <hr>
    <div class="row">
      <div class="col">
        {% block content %}
        {% endblock %}
      </div>
      <div class="col-3">
        {% if request.user.is_authenticated %}
        <div class="d-flex justify-content-center">
          <a class="btn btn-primary" href="{% url 'question:ask' %}">Ask</a>
        </div>
        {% else %}
        <div class="d-flex justify-content-center">
          <a class="btn btn-primary disabled" href="">Ask</a>
        </div>
        {% endif %}
        <br>
        <h2 class="d-flex justify-content-center">Trending</h2>
        {% for question in trending %}
        <div class="">
          <a href="{% url 'question:question' slug=question.title %}"><span class="badge badge-light">{{ question.rating }} vote{{ question.rating|pluralize }}</span>  {{ question.title }}</a>
        </div>
        {% endfor %}
      </div>
    </div>
  </div>
  
  <footer>
    <div class="footer-copyright text-center py-3" >
      <a href="{% url 'question:index' %}"> Hasker</a>
    </div>
  </footer>
   <script src="{% static 'js/bootstrap.min.js' %}"></script>
  <script src="{% static 'js/jquery.slim.min.js' %}"></script>
  <script src="{% static 'js/main.js' %}"></script>
  <script src="https://unpkg.com/ionicons@5.1.2/dist/ionicons.js"></script>
</body>

</html>